apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 32000
  selector:
    app: cowsay
