# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: siddheshdike/cowsay
  tag: "latest"

service:
  type: NodePort
  port: 4499

