apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploymentss
spec:
  template:
    metadata:
      name: cowsay
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: siddheshdike/cowsay:$(tag)
        ports:
        - containerPort: 4499
        env:
        # Define the environment variable
        - name: tag
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: special-config
              # Specify the key associated with the value
              key: tags
  replicas: 1
  selector:
    matchLabels:
      app: cowsay


    