apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploymentss
spec:
  template:
    metadata:
      name: cowsay
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        env:
        - name: tagartifacts
          value: "latest"

        - name: value
          valueFrom:
              configMapKeyRef:
                name: special-config
                key: tags
        image: siddheshdike/cowsay:"$(tagartifacts)"
        ports:
        - containerPort: 4499
        
  replicas: 1
  selector:
    matchLabels:
      app: cowsay


    