apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploymentss
spec:
  template:
    metadata:
      name: cowsay
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: $DEMO_GREETING
        ports:
        - containerPort: 4499
        env:
        - name: DEMO_GREETING
          value: siddheshdike/cowsay:latest
        
  replicas: 1
  selector:
    matchLabels:
      app: cowsay


    
